### ISSUE TITLE
Not working on OSX 10.9

### ISSUE THREAD

**Issue by barabbassj** [Abhishaker17/Clocker#3]
Hi man,

thank you for your free app!! I really appreciate! I have osx 10.9 and APP is not working. any idea to fix that ?

thanks

**Comment by Abhishaker17** [comment]
Hey,

Thanks for reporting this issue. Checking this.

**Comment by barabbassj** [comment]
thanks!


Best,

Alberto

**Comment by Abhishaker17** [comment]
Hey Alberto,

Here's a Mavericks supported version attached. This might be buggy since the code was not written keeping Mavericks in mind.

Also, you might have to go to System Preferences --> Security & Privacy --> General tab, and for
Allow Apps downloaded from choose "Anywhere".

[Clocker-Mavericks.zip](https://github.com/Abhishaker17/Clocker/files/93188/Clocker-Mavericks.zip)

**Comment by barabbassj** [comment]
Wonderful job! thanks a lot


Best,

Alberto
